/-! # LeanStats.Plot.Protocol — typed model for panel WebSocket messages

This is the contract between lean-stats's JS panels and any consumer
(l3m, Jupyter, another agent). Both sides agree on these inductives.

Adding a new panel type or event means adding a constructor here AND
a case in the JS factory. Coupling them in one repo prevents drift.
-/

set_option autoImplicit false

namespace LeanStats.Plot.Protocol

-- ════════════════════════════════════════════════════════════
-- § Events: panel → consumer (user actions observed in the browser)
-- ════════════════════════════════════════════════════════════

/-- A user-driven action observed in a panel. Generated by JS, parsed by Lean consumers. -/
inductive PanelEvent where
  /-- User changed the selection (click, shift-click, histogram bar, lasso). -/
  | selectionChanged (selectedIndices : Array Nat) (description : String)
  /-- User clicked Checkpoint — current fits frozen. -/
  | checkpoint (numPanels : Nat) (numFits : Nat)
  /-- User clicked Keep — wants to pin current state to document. -/
  | keep (state : String)  -- JSON blob of full state
  /-- User changed a transform or degree (model changed). -/
  | modelChanged (description : String)
  /-- User excluded points. -/
  | excluded (indices : Array Nat)
  /-- User hid points. -/
  | hidden (indices : Array Nat)
  /-- User inverted selection. -/
  | selectionInverted (newCount : Nat)
  /-- User cleared selection. -/
  | selectionCleared
  deriving Repr

-- ════════════════════════════════════════════════════════════
-- § Commands: consumer → panel (LLM/agent drives the UI)
-- ════════════════════════════════════════════════════════════

/-- A command from the consumer back to the panel. Drives SharedState. -/
inductive PanelCommand where
  /-- Select exactly these points (replaces current selection). -/
  | select (indices : Array Nat)
  /-- Add points to current selection. -/
  | addToSelection (indices : Array Nat)
  /-- Remove points from selection. -/
  | removeFromSelection (indices : Array Nat)
  /-- Clear all selection. -/
  | clearSelection
  /-- Exclude selected points from fits. -/
  | excludeSelected
  /-- Include all excluded points back. -/
  | includeAll
  /-- Hide excluded points (not rendered). -/
  | hideExcluded
  /-- Show all hidden points. -/
  | showAll
  /-- Flip selection on visible points. -/
  | invertSelection
  /-- Add a new variable to the data. -/
  | addVariable (name : String) (values : Array Float) (varType : String)
  /-- Add a new panel. -/
  | addPanel (panelType : String) (config : String)  -- config as JSON string
  /-- Remove a panel by index. -/
  | removePanel (panelId : Nat)
  /-- Trigger a checkpoint (freeze current fits). -/
  | checkpoint
  /-- Set a panel's configuration (transform, degree, etc.). -/
  | setConfig (panelId : Nat) (key : String) (value : String)
  deriving Repr

-- ════════════════════════════════════════════════════════════
-- § Encoding: PanelCommand → JSON string (for sending to WebSocket)
-- ════════════════════════════════════════════════════════════

/-- Encode a command as a JSON string for the WebSocket. -/
def encodeCommand : PanelCommand → String
  | .select ids => s!"\{\"cmd\":\"select\",\"ids\":[{commaJoin ids}]}"
  | .addToSelection ids => s!"\{\"cmd\":\"addToSelection\",\"ids\":[{commaJoin ids}]}"
  | .removeFromSelection ids => s!"\{\"cmd\":\"removeFromSelection\",\"ids\":[{commaJoin ids}]}"
  | .clearSelection => "{\"cmd\":\"clearSelection\"}"
  | .excludeSelected => "{\"cmd\":\"excludeSelected\"}"
  | .includeAll => "{\"cmd\":\"includeAll\"}"
  | .hideExcluded => "{\"cmd\":\"hideExcluded\"}"
  | .showAll => "{\"cmd\":\"showAll\"}"
  | .invertSelection => "{\"cmd\":\"invertSelection\"}"
  | .addVariable name values varType =>
    s!"\{\"cmd\":\"addVariable\",\"name\":\"{name}\",\"values\":[{commaJoinF values}],\"type\":\"{varType}\"}"
  | .addPanel panelType config =>
    s!"\{\"cmd\":\"addPanel\",\"type\":\"{panelType}\",\"config\":{config}}"
  | .removePanel panelId => s!"\{\"cmd\":\"removePanel\",\"id\":{panelId}}"
  | .checkpoint => "{\"cmd\":\"checkpoint\"}"
  | .setConfig panelId key value =>
    s!"\{\"cmd\":\"setConfig\",\"id\":{panelId},\"key\":\"{key}\",\"value\":\"{value}\"}"
where
  commaJoin (arr : Array Nat) : String :=
    String.intercalate "," (arr.toList.map toString)
  commaJoinF (arr : Array Float) : String :=
    String.intercalate "," (arr.toList.map toString)

-- ════════════════════════════════════════════════════════════
-- § Parsing: JSON string → PanelEvent (from WebSocket)
-- ════════════════════════════════════════════════════════════

/-- Parse a JSON event string from the WebSocket. Simple key-matching parser. -/
def parseEvent (s : String) : Except String PanelEvent :=
  let has (needle : String) : Bool := (s.splitOn needle).length > 1
  if has "\"event\":\"selection\"" then
    let text := extractField s "text"
    .ok (.selectionChanged #[] text)
  else if has "\"event\":\"checkpoint\"" then
    .ok (.checkpoint 0 0)
  else if has "\"event\":\"keep\"" then
    .ok (.keep s)
  else if has "\"cmd\":\"clearSelection\"" then
    .ok .selectionCleared
  else if has "\"selection inverted\"" then
    .ok (.selectionInverted 0)
  else
    .error s!"unrecognized event: {s.take 80}"
where
  extractField (json : String) (field : String) : String :=
    let marker := "\"" ++ field ++ "\":\""
    let parts := json.splitOn marker
    if parts.length >= 2 then
      let after := parts.getD 1 ""
      (after.splitOn "\"").getD 0 ""
    else ""

end LeanStats.Plot.Protocol
